apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-simple-app
  namespace: default
spec:
  type: Java
  mode: cluster
  image: rajendar38/spark-simple-app:v9
  mainClass: com.example.app.MainSparkApp
  mainApplicationFile: local:///opt/spark/app.jar
  sparkVersion: 3.4.0
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 2
    memory: 1g
  sparkConf:
    "spark.ui.enabled": "true"
    "spark.ui.port": "4040"

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: spark-ui-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: spark-ui-vs
  namespace: default
spec:
  gateways:
  - spark-ui-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /spark-app
    rewrite:
      uri: /
    route:
    - destination:
        host: spark-simple-app-driver-svc.default.svc.cluster.local
        port:
          number: 4040

          ------
          apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: spark-ui-vs
  namespace: default
spec:
  gateways:
  - spark-ui-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /spark-app
    rewrite:
      uri: /
    route:
    - destination:
        host: spark-simple-app-driver-svc.default.svc.cluster.local
        port:
          number: 4040
    
